### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by timyerg** [Kari-Genomics-Lab/iDeLUCS#15]
Hello!
Unfortunately, I encountered a new error while running the tool:

```
Training Parameters:
sequence_file 	 -> out/Chimeras_removal/nonchimeras.fasta
n_clusters 	 -> 0
n_epochs 	 -> 30
n_mimics 	 -> 3
batch_sz 	 -> 256
GT_file 	 -> None
k 	 -> 5
optimizer 	 -> RMSprop
scheduler 	 -> None
weight 	 -> 0.25
lambda 	 -> 2.8
lr 	 -> 0.001
n_voters 	 -> 5
model_size 	 -> linear
plot 	 -> False
None
No. Sequences: 	 2,850
Min. Length: 	 1,226
Max. Length: 	 2,112
Avg. Length: 	 1,449.25
........... Training Model (5/5)................Traceback (most recent call last):
  File "/home/user/anaconda3/envs/env/bin/idelucs", line 8, in <module>
    sys.exit(main())
  File "/home/user/Nextcloud2/Projects/iDeLUCS/idelucs/__main__.py", line 317, in main
    run(args)
  File "/home/user/Nextcloud2/Projects/iDeLUCS/idelucs/__main__.py", line 153, in run
    clusterer.fit(latent )
  File "/home/user/anaconda3/envs/env/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 1205, in fit
    ) = hdbscan(clean_data, **kwargs)
  File "/home/user/anaconda3/envs/env/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 824, in hdbscan
    (single_linkage_tree, result_min_span_tree) = memory.cache(
  File "/home/user/anaconda3/envs/env/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/home/user/anaconda3/envs/env/lib/python3.10/site-packages/hdbscan/hdbscan_.py", line 265, in _hdbscan_prims_kdtree
    min_spanning_tree = mst_linkage_core_vector(X, core_distances, dist_metric, alpha)
  File "hdbscan/_hdbscan_linkage.pyx", line 55, in hdbscan._hdbscan_linkage.mst_linkage_core_vector
  File "hdbscan/_hdbscan_linkage.pyx", line 144, in hdbscan._hdbscan_linkage.mst_linkage_core_vector
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by zht23333** [comment]
Hey bro. May I ask how did you install it？ When I use "pip install idelucs", it always goes wrong.

**Comment by timyerg** [comment]
Hey bro. I am the same that already answered you in another issue [here](https://github.com/Kari-Genomics-Lab/iDeLUCS/issues/14#issue-2235837886). I think that pip installation should be fixed by developer. Meanwhile, you can install it following guide for how to install it from github repository by fixing name of the folder in the command for changing directory.

**Comment by zht23333** [comment]
Oh, sorry. Haha. Yeah, i have tried as what you said in last issue. But when i "idelucs -h ", it says that "idelucs: command not found..."

**Comment by timyerg** [comment]
@zht23333 I think if you will post your output from the terminal after installation in related issue (not this one, the one by the link above), it my help the developer to debug it.

**Comment by timyerg** [comment]
I solved this issue by installing another version of hdbscan (hdbscan-0.8.33).
But a new error was encountered. I will close this issue and create a new one.

**Comment by zht23333** [comment]
Oh I know what went wrong. I will try again. Thank you , bro.

**Comment by zht23333** [comment]
Excuse me for asking this, where are you from.
