### ISSUE TITLE
Unable to resolve error

### ISSUE THREAD

**Issue by tonibrook43** [Kari-Genomics-Lab/iDeLUCS#22]
Hi, 
I am trying to use iDelucs for clustering some genomic data using the CLI. However, when I run my command, I'm getting a weird error that I can't figure out how to resolve. Any help would be appreciated!

My command: 
idelucs --sequence_file=file.fna \
            --n_clusters=3 --n_epochs=35 \
            --scheduler=None --lambda=2.8 \
            --batch_sz=512 --n_mimics=3 >> output.txt

Command error:
Traceback (most recent call last):
  File "/miniconda3/envs/idelucs/bin/idelucs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/iDeLUCS/idelucs/__main__.py", line 317, in main
    run(args)
  File "/iDeLUCS/idelucs/__main__.py", line 200, in run
    print(f"ACC: {results['ACC']}")
                  ~~~~~~~^^^^^^^
KeyError: 'ACC'

**Comment by Larissa-11** [comment]
你好，这个问题你解决了吗？
